######################################
# Persistência
######################################

appendonly yes

appendfilename appendonly.aof

######################################
# Snapshots
######################################

save 60 1000

######################################
# Diretório
######################################

dir /data

######################################
# Segurança
######################################

protected-mode no

######################################
# Memória
######################################

maxmemory-policy allkeys-lru

######################################
# Logs
######################################

loglevel notice